import {BACKDROPS,CHARACTERS,dialogueFor} from './scenes.mjs?v=12';
import {propArt} from './scene-props.mjs?v=12';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function theatreMarkup(scene,cursor=0,preview=null,observed=new Set(),full=false){
 const line=preview?{speaker:'你',kind:scene.actor?'准备回应':'准备行动',text:preview,index:0,total:scene.dialogue.length}:dialogueFor(scene,cursor);
 const actor=CHARACTERS[scene.actor];
 const figure=actor?`<div class="scene-actor actor-${scene.actor} ${actor.pose}"><img src="./${actor.image}" alt="${actor.name}" decoding="async"><span class="actor-name">${actor.name}<small>${actor.role}</small></span></div>`:'';
 const object=propArt(scene.prop)?`<div class="scene-object object-${scene.prop} ${actor?'with-actor':''}">${propArt(scene.prop)}</div>`:'';
 const points=scene.observations.map((o,i)=>`<button class="scene-hotspot ${observed.has(i)?'watched':''}" data-hotspot="${i}" style="--x:${o.x}%;--y:${o.y}%" aria-label="观察：${esc(o.title)}" title="${esc(o.title)}"><i>${observed.has(i)?'✓':'+'}</i><span>${esc(o.title)}</span></button>`).join('');
 const controls=preview?'<button class="dialogue-return" data-return-dialogue>返回对话</button>':`<button class="dialogue-back" data-dialogue="-1" ${line.index===0?'disabled':''} aria-label="上一句">←</button><button class="dialogue-advance" data-dialogue="1" ${line.index===line.total-1?'disabled':''} aria-label="下一句">${line.index===line.total-1?'读完了':'下一句 →'}</button>`;
 return `<div class="cinema-stage backdrop-${scene.background} ${full?'full-cinema':''} ${actor?'has-character':'environment-scene'} ${preview?'reply-preview':''}" style="--cinema-image:url('./${BACKDROPS[scene.background]}')"><div class="scene-atmosphere" aria-hidden="true"></div>${object}${figure}<div class="scene-points">${points}</div><p class="cinema-caption">${esc(scene.caption)}</p><section class="dialogue-card ${preview?'preview':''}" aria-label="剧情对话"><div class="dialogue-speaker"><span class="speaker-badge">${esc(line.speaker.slice(0,1))}</span><b>${esc(line.speaker)}</b><small>${esc(line.kind)}</small><span class="dialogue-count">${preview?'尚未确认':`${line.index+1} / ${line.total}`}</span></div><p class="dialogue-text">${esc(line.text)}</p><div class="dialogue-controls"><button class="dialogue-log" data-transcript>对话记录</button><div>${controls}</div></div></section></div>`;
}
export function transcriptMarkup(lines){return lines.map(line=>`<div class="transcript-line"><b>${esc(line.speaker)}<small>${esc(line.kind)}</small></b><p>${esc(line.text)}</p></div>`).join('');}
