import {BACKDROPS,CHARACTERS,dialogueFor} from './scenes.mjs?v=13';
import {propArt} from './scene-props.mjs?v=13';
import {gearIcon} from './icons.mjs?v=13';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const artFor=prop=>prop?.startsWith('gear:')?gearIcon(prop.slice(5)):propArt(prop);
export function theatreMarkup(scene,cursor=0,preview=null,observed=new Set(),full=false){
 const line=typeof preview==='string'?{speaker:'你',kind:'准备回应',text:preview,index:0,total:1}:dialogueFor(scene,cursor);
 const actor=CHARACTERS[scene.actor];
 const figure=actor?`<div class="scene-actor actor-${scene.actor} ${actor.pose}"><img src="./${actor.image}" alt="${actor.name}" decoding="async"><span class="actor-name">${actor.name}<small>${actor.role}</small></span></div>`:'';
 const object=artFor(scene.prop)?`<div class="scene-object ${scene.prop?.startsWith('gear:')?'scene-gear':`object-${scene.prop}`} ${actor?'with-actor':''}">${artFor(scene.prop)}</div>`:'';
 const points=scene.observations.map((o,i)=>`<button class="scene-hotspot ${observed.has(i)?'watched':''}" data-hotspot="${i}" style="--x:${o.x}%;--y:${o.y}%" aria-label="观察：${esc(o.title)}" title="${esc(o.title)}"><i>${observed.has(i)?'✓':'+'}</i><span>${esc(o.title)}</span></button>`).join('');
 const controls=`<button class="dialogue-back" data-dialogue="-1" ${line.index===0?'disabled':''} aria-label="上一句">←</button><button class="dialogue-advance" data-dialogue="1" ${line.index===line.total-1?'disabled':''} aria-label="下一句">${line.index===line.total-1?'读完了':'下一句 →'}</button>`;
 const cue=preview?`<div class="option-cue"><small>${scene.blocked?'条件不足 · 可查看设想':'选项情境 · 尚未执行'} · ${line.index+1} / ${line.total}</small><b>${esc(scene.title||'准备回应')}</b></div>`:'';
 return `<div class="cinema-stage backdrop-${scene.background} ${full?'full-cinema':''} ${actor?'has-character':'environment-scene'} ${preview?'reply-preview':''}" style="--cinema-image:url('./${BACKDROPS[scene.background]}')"><div class="scene-atmosphere" aria-hidden="true"></div>${object}${figure}<div class="scene-points">${points}</div><p class="cinema-caption">${esc(scene.caption)}</p><section class="dialogue-card ${preview?'preview':''}" aria-label="${preview?'选项情境':'剧情对话'}">${cue}<div class="dialogue-speaker"><span class="speaker-badge">${esc(line.speaker.slice(0,1))}</span><b>${esc(line.speaker)}</b><small>${esc(line.kind)}</small><span class="dialogue-count">${preview?'尚未确认 · ':''}${line.index+1} / ${line.total}</span></div><p class="dialogue-text">${preview?`${esc(line.speaker)}：`:''}${esc(line.text)}</p><div class="dialogue-controls"><button class="dialogue-log" data-transcript>情境记录</button><div>${controls}${preview?'<button class="dialogue-return" data-return-dialogue>返回现场</button>':''}</div></div></section></div>`;
}
export function optionCardMarkup(action,scene,number,selected=false,minutes=''){
 return `<button type="button" class="choice choice-vignette ${selected?'selected':''} ${action.disabled?'unavailable':''}" data-main="${esc(action.id)}" title="${esc(action.title+'：'+scene.summary+(action.disabled?' '+action.disabled:''))}" aria-pressed="${selected}"><span class="choice-number">${number}</span><span class="choice-visual" style="--option-image:url('./${BACKDROPS[scene.background]}')" aria-hidden="true">${artFor(scene.prop)}</span><div class="choice-copy"><strong>${esc(action.title)}</strong><p class="choice-situation">${esc(scene.summary)}</p><small class="choice-detail ${action.disabled?'choice-requirement':''}">${esc(action.disabled||action.desc)}</small></div><span class="choice-time">${minutes}</span></button>`;
}
export function transcriptMarkup(lines){return lines.map(line=>`<div class="transcript-line"><b>${esc(line.speaker)}<small>${esc(line.kind)}</small></b><p>${esc(line.text)}</p></div>`).join('');}
